export const placeHolder = {
  adult: false,
  backdrop_path: "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
  belongs_to_collection: {
    id: 727761,
    name: "",
    poster_path: "",
    backdrop_path: "",
  },
  budget: 250000,
  genres: [],
  homepage: "",
  id: 663712,
  imdb_id: "tt10403420",
  original_language: "en",
  original_title: "",
  overview: "",
  popularity: 1122.871,
  poster_path: "/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg",
  production_companies: [
    {
      id: 15157,
      logo_path: "/yezzLb9RbKNtQUsyYySAqC9TQr7.png",
      name: "Bloody Disgusting",
      origin_country: "US",
    },
    {
      id: 84591,
      logo_path: null,
      name: "Dark Age Cinema",
      origin_country: "",
    },
    {
      id: 114220,
      logo_path: null,
      name: "Fuzz on the Lens Productions",
      origin_country: "",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2022-10-06",
  revenue: 12400000,
  runtime: 138,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "",
  title: "",
  video: false,
  vote_average: 6.979,
  vote_count: 893,
};
